---
- name: make sure docker is running
  systemd:
    name: docker
    state: reloaded
    
- name: get cluster status
  shell: "oc cluster status"
  ignore_errors: true
  register: cluster_status
  environment:
    PATH: "{{ bins }}:{{ ansible_env.PATH }}"

- name:
  debug:
    msg: "{{ cluster_status }}"

- name: start cluster
  shell: "oc cluster up"
  environment:
    PATH: "{{ bins }}:{{ ansible_env.PATH }}"
  when: cluster_status.rc == 1
