---
- name: stat origin repo
  stat:
    path: "{{ repo_dir }}"
  register: repo_stat

- name: checkout origin
  git:
    repo: "{{ git_repo | default('https://github.com/openshift/origin.git') }}"
    dest: "{{ repo_dir }}"
    remote: "{{ git_remote | default(omit) }}"
    version: "{{ git_version | default(omit) }}"

- name: check
  shell: "cat {{ repo_dir }}/dummy.md"

- name: build origin
  shell: hack/build-go.sh
  args:
    chdir: "{{ repo_dir }}"
  when: make | default(true) | bool

- name: build local images
  shell: OS_DEBUG=true hack/build-local-images.py
  args:
    chdir: "{{ repo_dir }}"
  when: make | default(true) | bool
